//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_users
    {
        public int id { get; set; }
        public string email { get; set; }
        public string encrypted_password { get; set; }
        public string reset_password_token { get; set; }
        public Nullable<System.DateTime> reset_password_sent_at { get; set; }
        public Nullable<System.DateTime> remember_created_at { get; set; }
        public int sign_in_count { get; set; }
        public Nullable<System.DateTime> current_sign_in_at { get; set; }
        public Nullable<System.DateTime> last_sign_in_at { get; set; }
        public string current_sign_in_ip { get; set; }
        public string last_sign_in_ip { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
