//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_settings
    {
        public int id { get; set; }
        public int application_id { get; set; }
        public int test_id { get; set; }
        public string source { get; set; }
        public Nullable<short> expires_in { get; set; }
        public Nullable<short> max_retries { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual applications applications { get; set; }
        public virtual tests tests { get; set; }
    }
}
