//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaigns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campaigns()
        {
            this.campaign_test_appearances = new HashSet<campaign_test_appearances>();
            this.executions = new HashSet<executions>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string slug { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int application_id { get; set; }
        public string client_name { get; set; }
        public Nullable<bool> finished { get; set; }
        public string logo_file_name { get; set; }
        public string logo_content_type { get; set; }
        public Nullable<int> logo_file_size { get; set; }
        public Nullable<System.DateTime> logo_updated_at { get; set; }
        public string color { get; set; }
        public int number_of_resends { get; set; }
        public int number_of_resets { get; set; }
    
        public virtual applications applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campaign_test_appearances> campaign_test_appearances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<executions> executions { get; set; }
    }
}
