//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign_test_appearances
    {
        public int id { get; set; }
        public Nullable<int> campaign_id { get; set; }
        public Nullable<int> test_appearance_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string email_content { get; set; }
    
        public virtual test_appearances test_appearances { get; set; }
        public virtual campaigns campaigns { get; set; }
    }
}
