//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class executions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public executions()
        {
            this.captured_emails = new HashSet<captured_emails>();
            this.evaluation_send_logs = new HashSet<evaluation_send_logs>();
            this.execution_answers = new HashSet<execution_answers>();
            this.execution_competence_evaluations = new HashSet<execution_competence_evaluations>();
            this.execution_evaluations = new HashSet<execution_evaluations>();
            this.execution_steps = new HashSet<execution_steps>();
            this.minimo_english_test_data = new HashSet<minimo_english_test_data>();
        }
    
        public int id { get; set; }
        public int test_id { get; set; }
        public int test_appearance_id { get; set; }
        public int application_user_id { get; set; }
        public short retries { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> finish_time { get; set; }
        public Nullable<System.DateTime> valid_until { get; set; }
        public Nullable<System.DateTime> discard_time { get; set; }
        public Nullable<bool> external { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<short> rating { get; set; }
        public string type { get; set; }
        public Nullable<int> campaign_id { get; set; }
    
        public virtual application_users application_users { get; set; }
        public virtual campaigns campaigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<captured_emails> captured_emails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evaluation_send_logs> evaluation_send_logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<execution_answers> execution_answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<execution_competence_evaluations> execution_competence_evaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<execution_evaluations> execution_evaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<execution_steps> execution_steps { get; set; }
        public virtual test_appearances test_appearances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<minimo_english_test_data> minimo_english_test_data { get; set; }
        public virtual tests tests { get; set; }
    }
}
