//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class execution_steps
    {
        public int id { get; set; }
        public int execution_id { get; set; }
        public int test_section_id { get; set; }
        public short position { get; set; }
        public string status { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> spent_time { get; set; }
    
        public virtual executions executions { get; set; }
        public virtual test_sections test_sections { get; set; }
    }
}
