//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class execution_competence_evaluations
    {
        public int id { get; set; }
        public int execution_id { get; set; }
        public int test_competence_id { get; set; }
        public Nullable<int> test_profile_id { get; set; }
        public Nullable<decimal> score { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual test_competences test_competences { get; set; }
        public virtual test_profiles test_profiles { get; set; }
        public virtual executions executions { get; set; }
    }
}
