//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class execution_answers
    {
        public int id { get; set; }
        public int execution_id { get; set; }
        public int test_section_question_id { get; set; }
        public int test_section_question_option_id { get; set; }
        public decimal extra_score { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual executions executions { get; set; }
        public virtual test_section_questions test_section_questions { get; set; }
        public virtual test_section_question_options test_section_question_options { get; set; }
    }
}
