//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BetthaEntities : DbContext
    {
        public BetthaEntities()
            : base("name=BetthaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<active_admin_comments> active_admin_comments { get; set; }
        public virtual DbSet<admin_users> admin_users { get; set; }
        public virtual DbSet<application_settings> application_settings { get; set; }
        public virtual DbSet<application_users> application_users { get; set; }
        public virtual DbSet<applications> applications { get; set; }
        public virtual DbSet<campaign_test_appearances> campaign_test_appearances { get; set; }
        public virtual DbSet<campaign_user_infos> campaign_user_infos { get; set; }
        public virtual DbSet<campaigns> campaigns { get; set; }
        public virtual DbSet<captured_emails> captured_emails { get; set; }
        public virtual DbSet<evaluation_send_logs> evaluation_send_logs { get; set; }
        public virtual DbSet<execution_answers> execution_answers { get; set; }
        public virtual DbSet<execution_competence_evaluations> execution_competence_evaluations { get; set; }
        public virtual DbSet<execution_evaluations> execution_evaluations { get; set; }
        public virtual DbSet<execution_steps> execution_steps { get; set; }
        public virtual DbSet<executions> executions { get; set; }
        public virtual DbSet<media_elements> media_elements { get; set; }
        public virtual DbSet<minimo_english_test_data> minimo_english_test_data { get; set; }
        public virtual DbSet<test_appearance_pages> test_appearance_pages { get; set; }
        public virtual DbSet<test_appearances> test_appearances { get; set; }
        public virtual DbSet<test_competences> test_competences { get; set; }
        public virtual DbSet<test_levels> test_levels { get; set; }
        public virtual DbSet<test_profile_ranges> test_profile_ranges { get; set; }
        public virtual DbSet<test_profiles> test_profiles { get; set; }
        public virtual DbSet<test_section_question_options> test_section_question_options { get; set; }
        public virtual DbSet<test_section_questions> test_section_questions { get; set; }
        public virtual DbSet<test_section_types> test_section_types { get; set; }
        public virtual DbSet<test_sections> test_sections { get; set; }
        public virtual DbSet<tests> tests { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<schema_migrations> schema_migrations { get; set; }
    }
}
