//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_competences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public test_competences()
        {
            this.execution_competence_evaluations = new HashSet<execution_competence_evaluations>();
            this.test_sections = new HashSet<test_sections>();
            this.test_section_question_options = new HashSet<test_section_question_options>();
        }
    
        public int id { get; set; }
        public int test_id { get; set; }
        public string name { get; set; }
        public bool deprecated { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string key { get; set; }
        public string extra_info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<execution_competence_evaluations> execution_competence_evaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_sections> test_sections { get; set; }
        public virtual tests tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_section_question_options> test_section_question_options { get; set; }
    }
}
