//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_sections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public test_sections()
        {
            this.execution_steps = new HashSet<execution_steps>();
            this.test_section_questions = new HashSet<test_section_questions>();
            this.test_appearances = new HashSet<test_appearances>();
        }
    
        public int id { get; set; }
        public int test_level_id { get; set; }
        public int test_section_type_id { get; set; }
        public Nullable<int> test_competence_id { get; set; }
        public Nullable<short> position { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public bool important { get; set; }
        public bool deprecated { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<execution_steps> execution_steps { get; set; }
        public virtual test_competences test_competences { get; set; }
        public virtual test_levels test_levels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_section_questions> test_section_questions { get; set; }
        public virtual test_section_types test_section_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_appearances> test_appearances { get; set; }
    }
}
