//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bettha_Scoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_appearance_pages
    {
        public int id { get; set; }
        public int test_appearance_id { get; set; }
        public Nullable<int> test_profile_id { get; set; }
        public string type { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public bool deprecated { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual test_profiles test_profiles { get; set; }
        public virtual test_appearances test_appearances { get; set; }
    }
}
